### ISSUE TITLE
Works with 10.0.3 and 10.0.4

### ISSUE THREAD

**Issue by designgears** [suchmememanyskill/EmmcHaccGen#1]
Tested and works fine with latest firmware.

**Comment by suchmememanyskill** [comment]
Thanks for the heads up! firmware table has been updated

**Comment by designgears** [comment]
Works with 10.1.0 as well.

![image](https://user-images.githubusercontent.com/799451/87449478-7ffb8380-c5ba-11ea-827a-3a3d2ae1a3a3.png)
![image](https://user-images.githubusercontent.com/799451/87449540-8be74580-c5ba-11ea-82d3-67a1212dac25.png)
