### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by rickoone** [suchmememanyskill/EmmcHaccGen#10]
I have win7 with Java installed and .net3.1 and app while started throws an error....
Please help
![P_20210616_083632.jpg](https://user-images.githubusercontent.com/19279820/122169683-f87b5c00-ce7d-11eb-922e-01421524bd04.jpg)

**Comment by suchmememanyskill** [comment]
Github issues is not the place to ask for support. Seek support in my discord ( https://discord.gg/aH9rsuP ). Also, have you tried `dotnet emmchaccgen.dll (args)`
