### ISSUE TITLE
Problems with NET Core

### ISSUE THREAD

**Issue by iCRON862** [suchmememanyskill/EmmcHaccGen#3]
I installed NET Core 5.0 and the Programm give the same error and i don‘t know how and where must install NET Core in order to can use the programm to unbrick my switch. 

picture: 
![image](https://user-images.githubusercontent.com/39169140/101237954-16048780-36dd-11eb-8c95-069512b8cbb5.jpg)

**Comment by suchmememanyskill** [comment]
Emmchaccgen needs .net core 3.1, not 5.0
