### ISSUE TITLE
EmmcHaccGen cannot build working firmware 11.0.0 and 11.0.1

### ISSUE THREAD

**Issue by Anarhist8BIT** [suchmememanyskill/EmmcHaccGen#6]
after writing the conscious firmware EmmcHaccGen 11.0.0 and 11.0.1 hangs on the last logo

**Comment by suchmememanyskill** [comment]
i cannot reproduce this issue, on both 11.0.0 and 11.0.1. you'd need to provide more information. Also define "hangs on the last logo". Do you mean the switch logo? does it not show up at all or does it just do nothing with the switch logo shown?

**Comment by Anarhist8BIT** [comment]
reaches the last logo and hangs on it 
https://sun9-64.userapi.com/impg/chfAEiEPa3lpeJAe-snXAmBEy-hYq-dUJwlIWg/yHS6e5zEa28.jpg?size=2560x1440&quality=96&proxy=1&sign=45f05746563efe59d41ab7502179698d&type=album

**Comment by suchmememanyskill** [comment]
are you testing this with cfw or stock? this kind of sounds like an issue with cfw files

**Comment by Anarhist8BIT** [comment]
cfw (emuNAND)

**Comment by suchmememanyskill** [comment]
get a fresh cfw setup. This is unlikely to be an issue with emmchaccgen

**Comment by Anarhist8BIT** [comment]
hekate - CTCaer mod v5.5.2 \ Atmosphere 0.17.0

**Comment by Anarhist8BIT** [comment]
@suchmememanyskill runoff and cwf works if i write to emmc, if i use emuNand hangs on the logo

**Comment by suchmememanyskill** [comment]
again, unlikely to be an issue here. if it shows the switch logo everything that emmchaccgen generates checks out. this is likely an issue elsewhere

**Comment by Anarhist8BIT** [comment]
@suchmememanyskill  well, thanks, I will understand. I'm looking forward to more support from mariko EmmcHaccGen
