### ISSUE TITLE
'Keyset file not found' Error

### ISSUE THREAD

**Issue by emilybjackson** [suchmememanyskill/EmmcHaccGen#7]
I have confirmed that my prod.keys file is in the same folder as EmmcHaccGen but when I run the command I get this error: "Keyset file not found". I got the prod.keys file from Lockpick. Can you tell me if I'm doing something incorrectly?
<img width="903" alt="Screen Shot 2021-02-04 at 10 11 14 AM" src="https://user-images.githubusercontent.com/78559715/106936426-67c39100-66d1-11eb-9515-1bb622a01a42.png">

**Comment by suchmememanyskill** [comment]
You are running the exe from another location. Cd into the emmchaccgen folder first, then execute `emmchaccgen.exe ...`

**Comment by emilybjackson** [comment]
THANK YOUUU. Got it working! Thanks so much for your contribution, you just saved me and my switch.
