### ISSUE TITLE
There is something not right when generating the system files for the lite.

### ISSUE THREAD

**Issue by sthetix** [suchmememanyskill/EmmcHaccGen#8]
Hi, I tried to generate the switch lite system files with emmchaccgen, but it seems that it generated the system files for the regular or phat console. Because when I reset the system, I need to connect the console to the tv and remove the joycon, but as you know there is nothing like that on the Lite. So, can you check that out?

Btw, generating the system files with these keys..

header_key =
key_area_key =
save_mac_key =

has no difference than generating it with the full keys 

of course, I have put --mariko at the end of the command.

**Comment by suchmememanyskill** [comment]
Why did you close and re-open it? I can't exactly do anything about this

**Comment by sthetix** [comment]
> Why did you close and re-open it? I can't exactly do anything about this


Sorry, this issue is more important than the previous one.

**Comment by suchmememanyskill** [comment]
this is an entirely different issue. open a new issue

i'm currently submitting a request to microsoft, hopefully to get the false detection resolved
