### ISSUE TITLE
emmchaccgen

### ISSUE THREAD

**Issue by josken69** [suchmememanyskill/EmmcHaccGen#9]
downloaded emmchac gen but it wont open i my laptop any help loading would be a great help
thank you

**Comment by suchmememanyskill** [comment]
You are not very descriptive about your issue. Define "it won't open"

**Comment by josken69** [comment]
sorry new to this have downloaded the zip file of emmchaccgen and extracted it to desk top but when i click on application nothing happens i normally repair the hardware on the switches but have got one that has an error on thee boot0 and want to get into the software side  do i open it with the cmd prompt and if so what do i type sorry like i said new to this so any help with a walk through would be great as can not find any help on the web

**Comment by suchmememanyskill** [comment]
It is a commandline application, so double clicking it will do nothing, you have to use it via cmd. See the readme (or type `emmchaccgen.exe -h`) for what it can do. See also https://suchmememanyskill.github.io/guides/unbrick . Also github issues is not for support. Seek support in the discord

**Comment by josken69** [comment]
Ok thanks have got it sorted now

Sent from Mail for Windows 10
